language: objective-c
osx_image: xcode10
# xcode_workspace: ApplepieDemo/ApplepieDemo.xcworkspace
# xcode_scheme: ApplepieDemo
# xcode_sdk: iphonesimulator12.0
podfile: ApplepieDemo/Podfile

branches:
  only:
  - master

-before_install:
 - |
    pod repo update
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    set -o pipefail
    xcodebuild clean test -workspace ApplepieDemo/ApplepieDemo.xcworkspace -scheme ApplepieDemo -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.0' -enableCodeCoverage YES | bundle exec xcpretty
after_success:
    - sleep 5
    - bash <(curl -s https://codecov.io/bash)