language: objective-c
osx_image: xcode10
# xcode_workspace: ApplepieDemo/ApplepieDemo.xcworkspace
# xcode_scheme: ApplepieDemo
# xcode_sdk: iphonesimulator12.0
podfile: ApplepieDemo/Podfile

-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    set -o pipefail
    xcodebuild clean test -workspace ApplepieDemo/ApplepieDemo.xcworkspace -scheme ApplepieDemo -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' -enableCodeCoverage YES | bundle exec xcpretty
